// Code Generated by Sidekick is for learning and experimentation purposes only.
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { CollaboratorService } from '../../services/collaborator/collaborator.service';
import { EmployeeService } from '../../services/employee/employee.service';


@Component({
  selector: 'app-manage-collaborator',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, FormsModule],
  templateUrl: './manage-collaborator.component.html'
})
export class ManageCollaboratorComponent implements OnInit {
  // Collaborator data
  collaborators: any[] = [];
  collaboratorForm: FormGroup;
  loadingCollaborators = false;
  errorCollaborators = '';
  success = '';
  showConfirmModal = false;
  pendingDeleteEmail = '';

  // Employee data & filters
  employees: any[] = [];
  totalEmployees = 0;
  bands: string[] = [];
  roles: string[] = [];
  skillLevels: string[] = [];
  selectedBand = '';
  selectedRole = '';
  selectedSkillLevel = '';
  search = '';
  loadingEmployees = false;
  errorEmployees = '';

  // For selecting an employee to add as collaborator
  selectedEmployeeEmail = '';

  constructor(
    private collaboratorService: CollaboratorService,
    private employeeService: EmployeeService,
    private fb: FormBuilder
  ) {
    this.collaboratorForm = this.fb.group({
      collaborator_email: ['', [Validators.required, Validators.email]],
      topics: [false],
      test_create: [false],
      test_assign: [false]
    });
  }

  ngOnInit() {
    this.loadCollaborators();
    this.loadEmployeeFilters();
    this.loadEmployees();
  }

  // --- Collaborator Logic ---
  loadCollaborators() {
    this.loadingCollaborators = true;
    this.errorCollaborators = '';
    this.collaboratorService.getCollaborators().subscribe({
      next: (data) => {
        this.collaborators = data || [];
        this.loadingCollaborators = false;
      },
      error: (err: any) => {
        // Graceful error handling
        this.errorCollaborators = err?.error?.detail || 'Unable to load collaborators. Please try again later.';
        this.loadingCollaborators = false;
      }
    });
  }

  submitForm() {
    if (this.collaboratorForm.invalid) return;
    this.success = '';
    this.errorCollaborators = '';
    this.collaboratorService.upsertCollaborator(this.collaboratorForm.value).subscribe({
      next: () => {
        this.success = 'Collaborator added/updated successfully';
        this.loadCollaborators();
        this.collaboratorForm.reset({ topics: false, test_create: false, test_assign: false });
        setTimeout(() => this.success = '', 2500);
      },
      error: (err: any) => {
        this.errorCollaborators = err?.error?.detail || 'Failed to add/update collaborator. Please check the email and permissions.';
        setTimeout(() => this.errorCollaborators = '', 3000);
      }
    });
  }

  confirmDelete(email: string) {
    this.pendingDeleteEmail = email;
    this.showConfirmModal = true;
  }

  deleteCollaborator() {
    this.showConfirmModal = false;
    this.collaboratorService.deleteCollaborator(this.pendingDeleteEmail).subscribe({
      next: () => {
        this.success = 'Collaborator deleted successfully';
        this.loadCollaborators();
        setTimeout(() => this.success = '', 2500);
      },
      error: (err: any) => {
        this.errorCollaborators = err?.error?.detail || 'Failed to delete collaborator.';
        setTimeout(() => this.errorCollaborators = '', 3000);
      }
    });
  }

  cancelDelete() {
    this.showConfirmModal = false;
    this.pendingDeleteEmail = '';
  }

  // --- Employee Logic ---
  loadEmployeeFilters() {
    this.employeeService.getEmployeeFilterOptions().subscribe({
      next: (data: any) => {
        this.bands = data.bands || [];
        this.roles = data.roles || [];
        this.skillLevels = data.skill_levels || data.skills || [];
      },
      error: (error: any) => {
        this.errorEmployees = 'Failed to load filter options. Please try again later.';
      }
    });
  }

  loadEmployees() {
    this.loadingEmployees = true;
    this.errorEmployees = '';
    const params: any = {};
    if (this.selectedBand) params.band = this.selectedBand;
    if (this.selectedRole) params.designation = this.selectedRole;
    if (this.selectedSkillLevel) params.skill_level = this.selectedSkillLevel;
    if (this.search) params.search = this.search;

    this.employeeService.getEmployees(params).subscribe({
      next: (data: any) => {
        this.employees = data.employees || [];
        this.totalEmployees = data.total || 0;
        this.loadingEmployees = false;
      },
      error: (error: any) => {
        this.errorEmployees = 'Failed to load employees. Please try again later.';
        this.loadingEmployees = false;
      }
    });
  }

  onEmployeeFilterChange() {
    this.loadEmployees();
  }

  selectEmployee(email: string) {
    this.selectedEmployeeEmail = email;
    this.collaboratorForm.patchValue({ collaborator_email: email });
  }

  clearEmployeeSelection() {
    this.selectedEmployeeEmail = '';
    this.collaboratorForm.patchValue({ collaborator_email: '' });
  }

  clearAllFilters() {
    this.selectedBand = '';
    this.selectedRole = '';
    this.selectedSkillLevel = '';
    this.search = '';
    this.onEmployeeFilterChange();
  }

  hasActiveFilters(): boolean {
    return !!(this.selectedBand || this.selectedRole || this.selectedSkillLevel || this.search);
  }
}
