// Code Generated by Sidekick is for learning and experimentation purposes only.
import { Injectable } from '@angular/core';
import { CanActivate, Router } from '@angular/router';
import { LoginService } from '../services/login/login.service';
@Injectable({ providedIn: 'root' })
export class LoginGuard implements CanActivate {
  constructor(private auth: LoginService, private router: Router) {}

  canActivate(): boolean {
    if (this.auth.isAuthenticated()) {
        const role = this.auth.getUserRole();
        if(role == 'DeliveryLeader' || role == 'DeliveryManager' || role == 'ProductManager'){
            this.router.navigate(['/delivery-manager-dashboard']);
        }
        else if(role == 'CapabilityLeader'){
            this.router.navigate(['/capability-leader-dashboard']);
        }
        else{
            this.router.navigate(['/employee-dashboard']);
        }
      return false;
    }
    return true;
  }
}
