FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app
EXPOSE 8080
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]

#COPY requirements.txt /app/requirements.txt
#ENTRYPOINT ["python", "./launch.py"]
# docker build -t dmaharajanm/helloworld-pythonapp .
# docker run -d -p 5000:5000 --name=helloworld-pythonapp dmaharajanm/helloworld-pythonapp